version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  k6:
    image: grafana/k6:latest
    container_name: k6
    networks:
      - app-tier
    ports:
      - "6565:6565"
    volumes:
      - ${PWD}/scripts/k6/:/scripts
