version: "3.9"
networks:
  app-tier:
    driver: bridge

services:
  api:
    image: dcard-ad-backend
    restart: always
    env_file:
      - ${PWD}/.env
    depends_on:
      - mongodb
    ports:
      - 80:80
    networks:
      - app-tier

  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    networks:
      - app-tier
    restart: always

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-tier

volumes:
  mongo-data:
