### API
POST http://localhost/api/v1/ad
Content-Type: application/json

{
    "title": "AD 1",
    "startAt": "{{ $datetime 'YYYY-MM-DDTHH:mm:ssZ' -5 h }}",
    "endAt": "{{ $datetime 'YYYY-MM-DDTHH:mm:ssZ' 3 d }}",
    "conditions": {
        "ageStart": 20,
        "ageEnd": 50,
        "gender": ["F"],
        "country": ["TW", "JP","US"],
        "platform": ["android", "ios"]
    }
}

###
GET http://localhost/api/v1/ad?offset=0&limit=3&age=25&gender=F&country=TW&platform=ios
Content-Type: application/json


###
GET http://localhost/api/v1/ad?offset=0&limit=5&age=44
Content-Type: application/json